M2m2 simple dev
ROAR-QUTRC/perseus-v2 pull request #35
Opened 2024-12-22 12:03 UTC by DingoOz

This PR brings over the Humble baseline code for the m2m2_lidar node. 

I added the nlohmann and openSSL libraries to the pacakge's nix overlay. 

When adding these libraries to the CMakeLists.txt I had to add a target_link_libraries explicitly as there are two libraries in OpenSSL that are needed OpenSSL::SSL and Open::Crypto and build fails unless being explicit here. 

This is the relevant section:
# OpenSSL has two libraries that need to linked against explicitly
target_link_libraries(
  m2m2_lidar
  PRIVATE OpenSSL::SSL OpenSSL::Crypto nlohmann_json::nlohmann_json
          ${rclcpp_LIBRARIES} ${sensor_msgs_LIBRARIES} ${std_msgs_LIBRARIES})

2024-12-22 14:13 UTC, RandomSpaceship requested changes
I've gone through and commented on most of the issues I see. Probably missed a few things, but I think I've noted the worst of it.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    struct SensorConfig
naming doesn't match software standards - should be `sensor_config_t`

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/package.xml
> +  <depend>sensor_msgs</depend>
if you depend on openSSL and nlohman::json, add the dependencies here. Just standard `<depend>` tags in this case, `openssl` and `nlohmann-json-dev`.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/CMakeLists.txt
> +          ${rclcpp_LIBRARIES} ${sensor_msgs_LIBRARIES} ${std_msgs_LIBRARIES})
replace all of this with:
```
target_link_libraries(m2m2_lidar PRIVATE OpenSSL::Crypto)
```
That's all you need.

`target_link_libraries` is not exclusive, it's additive! `ament_target_dependencies` already sets up linking against all of the dependencies in `THIS_PACKAGE_INCLUDE_DEPENDS`, getting rid of all the `_LIBRARIES` specifiers you have there. Its [documentation](https://docs.ros.org/en/jazzy/How-To-Guides/Ament-CMake-Documentation.html#linking-to-dependencies) shows in the example that it also links against default namespaced targets too, so that gets rid of `OpenSSL::SSL` and `nlohmann_json::nlohmann_json` (I think they're the default targets), which leaves only `OpenSSL::Crypto` needing manual linking.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    ~M2M2Lidar();
heed the [Rule of Three](https://roar-qutrc.github.io/standards/software.html#rule-of-three) - given that you have a destructor (and are therefore probably managing resources), you almost certainly need to handle copy/move semantics as well, even if it's just `delete`ing them. Since you _are_ managing resources (network socket), you definitely need to handle it.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    static constexpr const char* REQUEST_DELIM = "\r\n\r\n";
incorrect [ordering](https://roar-qutrc.github.io/standards/software.html#member-ordering)

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    this->declare_parameter("sensor_ip", "192.168.1.243");
doesn't it have a hostname you can use instead? This won't work on any network except your own

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    }
yes this will get replaced with a network library, but I'd still strongly recommend reading through [this guide](https://beej.us/guide/bgnet/html) (specifically see `getaddrinfo`). The code you have is the old way of doing things

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    if (::connect(_socket, (struct sockaddr*)&serverAddr, sizeof(serverAddr)) < 0)
why the scope resolution operator?

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        .maxRange = 30.0};
I like to add a comma after the last operator so the ending brace is placed on a newline, but that's preference. Should see if there's a clang-format option to do it automatically

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    return decoded;
looks like there aren't any good standalone libraries in the ROS index. This looks a lot easier to use than the `BIO_` interface though (although check the notes in the comments): https://stackoverflow.com/a/60580965/11732291

Using std::vector instead of calloc/malloc is good, though!

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    {
use [`strncmp`](https://cplusplus.com/reference/cstring/strncmp/), it makes your intent much clearer.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +                {  // Fixed condition
what's this comment doing?

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +                    decompressed.push_back(repeat_val);
use `.insert()` instead of this whole loop anyway https://stackoverflow.com/questions/30998444/add-same-value-multiple-times-to-stdvector-repeat

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        memcpy(&angle, &decompressed[i + 4], sizeof(float));
Use the C++ replacements (`std::copy` or `std::copy_n`) instead

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        bool valid = distance != 100000.0;
it's almost always a bad idea to do exact float comparisons. In this case, if it's working and it's what the documentation says to do, fine, but I would still suggest replacing it with a "within epsilon" check instead

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/CMakeLists.txt
> +set(THIS_PACKAGE_INCLUDE_DEPENDS rclcpp sensor_msgs std_msgs OpenSSL
you're not using `std_msgs`, so don't link against it

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +            received[received.size() - 1] == '\n')
same as before, use `strncmp`

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    serv_addr.sin_family = AF_INET;
lovely duplicated code. Same comments as before apply obviously. `tv` and `serv_addr` names both fail the software standards.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    if (!this->connectToSensor(_sensorAddress, _sensorPort))
... this is recursive? That's a bad idea! If the connection is failing, this code will enter infinite recursion and eventually crash, the if statement will never run

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +bool M2M2Lidar::connectToSensor(const std::string& host, int port)
why does it even take arguments when it's a member function and can just access the address + port directly?

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +bool M2M2Lidar::connectToSensor(const std::string& host, int port)
Also, try to avoid return codes for function success/failure. In this case it will succeed the majority of the time, so an exception is a better choice.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    command.push_back(static_cast<uint8_t>(config.angularResolution * 100));
you should clamp these before casting. static_cast will throw exceptions if the values can't be held in the specified type. See the VESC and MCB hardware interfaces (check both, they're slightly different) for examples of how to do it properly.

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    std::string base64_points = response["result"]["laser_points"];
naming check - not standard

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    auto scan = std::make_unique<sensor_msgs::msg::LaserScan>();
I don't think there's any good reason to use a pointer here instead of just using the type directly

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +};
don't use a different syntax. Declare **everything** which should be part of the class in the header file. Also, naming check fails again (method names + underscore placement).

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/nix-packages/perseus-sensors.nix
> +}
after fixing the `package.xml`, run `software/scripts/nix-package.sh --no-commit` to regenerate the nix packaging info

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    ~M2M2Lidar();
destructors should either be protected and nonvirtual or public and virtual

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    ~M2M2Lidar();
(yes I'm guilty of this too, I need to fix my code as well)

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +using namespace std::chrono_literals;
you might want to add `using std::string, std::vector;` and the like to remove some of the namespacing in this file

2024-12-22 14:13 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    scan->range_max = 30.0;                               // 30m maximum range
give your magic constants names, then you can also get rid of the comments (or convert them to notes on the units of the constant)

2024-12-22 23:30 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +            received[received.size() - 1] == '\n')
https://github.com/ROAR-QUTRC/perseus-v2/commit/6206d4981205212d3e737b1526e8cdb5d46b99cb

2024-12-22 23:30 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/CMakeLists.txt
> +set(THIS_PACKAGE_INCLUDE_DEPENDS rclcpp sensor_msgs std_msgs OpenSSL
https://github.com/ROAR-QUTRC/perseus-v2/commit/95632c52c4776f1245ac2b269c7f016052ff02af

2024-12-22 23:34 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    static constexpr const char* REQUEST_DELIM = "\r\n\r\n";
https://github.com/ROAR-QUTRC/perseus-v2/commit/33363778eef051fb6934b3653e13c5af73f7246b

2024-12-22 23:35 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    {
https://github.com/ROAR-QUTRC/perseus-v2/commit/6206d4981205212d3e737b1526e8cdb5d46b99cb

2024-12-22 23:35 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +                {  // Fixed condition
https://github.com/ROAR-QUTRC/perseus-v2/commit/399db158c573e688e357d47c383c0144d64610d5

2024-12-22 23:37 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/CMakeLists.txt
> +          ${rclcpp_LIBRARIES} ${sensor_msgs_LIBRARIES} ${std_msgs_LIBRARIES})
https://github.com/ROAR-QUTRC/perseus-v2/commit/f6d84acb96d431fd334be49ef36bd783c0ea1940

2024-12-22 23:39 UTC, DingoOz commented on software/ros_ws/nix-packages/perseus-sensors.nix
> +}
https://github.com/ROAR-QUTRC/perseus-v2/commit/bcc1dab94b0acade5d9aa748db2aa6e54341f003

2024-12-22 23:40 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        .maxRange = 30.0};
https://github.com/ROAR-QUTRC/perseus-v2/commit/2d5490d544f7b0e4dc58bb024e7076022a7169d0

2024-12-22 23:41 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        memcpy(&angle, &decompressed[i + 4], sizeof(float));
https://github.com/ROAR-QUTRC/perseus-v2/commit/606940f46e8f87277f8e40edd05eb96e5600cbf1

2024-12-22 23:42 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        bool valid = distance != 100000.0;
https://github.com/ROAR-QUTRC/perseus-v2/commit/529b9d4cf611ff262fff82475d3ffc10734ab2e3

2024-12-22 23:43 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    ~M2M2Lidar();
https://github.com/ROAR-QUTRC/perseus-v2/commit/298c6678cc0e92d484eb33b6fa0a05df7a8e3510

2024-12-22 23:44 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/package.xml
> +  <depend>sensor_msgs</depend>
https://github.com/ROAR-QUTRC/perseus-v2/commit/bcc1dab94b0acade5d9aa748db2aa6e54341f003

2024-12-23 02:17 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/CMakeLists.txt
> +# OpenSSL has two libraries that need to linked against explicitly
maybe update the comment?

2024-12-23 02:17 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    static constexpr const char* REQUEST_DELIM = "\r\n\r\n";
why not just use `std::string`?

2024-12-23 02:17 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/README.md
> +
this is already captured in the `package.xml`, why double it up?

2024-12-23 10:42 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/README.md
> +
https://github.com/ROAR-QUTRC/perseus-v2/commit/611e7981fee36ba347e42f59c9fb3c2395450b3b

2024-12-23 10:47 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    struct SensorConfig
https://github.com/ROAR-QUTRC/perseus-v2/commit/d35751a4f33f8f12fa390a249824abfeca8d07f2

2024-12-23 11:16 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    std::string base64_points = response["result"]["laser_points"];
https://github.com/ROAR-QUTRC/perseus-v2/commit/3c3358da50f7d4a7a4b0193802d6fed85174c730

https://github.com/ROAR-QUTRC/perseus-v2/commit/b80ff9cb253e83f499e77d5939744ad30278a402

https://github.com/ROAR-QUTRC/perseus-v2/commit/156a666cb2e0ee05374fd9d060fa9682a4d7f662

2024-12-23 11:48 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    auto scan = std::make_unique<sensor_msgs::msg::LaserScan>();
https://github.com/ROAR-QUTRC/perseus-v2/commit/c8d880714a718995b40a9f6111d894d20dab3893

2024-12-23 12:03 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    static constexpr const char* REQUEST_DELIM = "\r\n\r\n";
https://github.com/ROAR-QUTRC/perseus-v2/commit/78d0a19133ff401eb91af02336dc1533cda63f07

2024-12-23 12:05 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/CMakeLists.txt
> +# OpenSSL has two libraries that need to linked against explicitly
https://github.com/ROAR-QUTRC/perseus-v2/commit/487f92f9db202418177fa8804793ac9a15120956

2024-12-23 12:11 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    if (::connect(_socket, (struct sockaddr*)&serverAddr, sizeof(serverAddr)) < 0)
https://github.com/ROAR-QUTRC/perseus-v2/commit/621df83e32c765f597176ba71f0045d611400527

2024-12-23 12:17 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    this->declare_parameter("sensor_ip", "192.168.1.243");
No hostname available. Need to determine if we want the Orin to assign a static IP address to it or use another method of determining IP address. Future feature will be to receive IP address via param. 

dig output:
; <<>> DiG 9.18.28-0ubuntu0.22.04.1-Ubuntu <<>> -x 192.168.1.243
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26380
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;243.1.168.192.in-addr.arpa.	IN	PTR

;; Query time: 7 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Dec 23 22:13:21 AEST 2024
;; MSG SIZE  rcvd: 55

2024-12-23 20:13 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    scan->range_max = 30.0;                               // 30m maximum range
https://github.com/ROAR-QUTRC/perseus-v2/commit/4806ae84d7e1551f47f4ee6f0179b2ee788e2561

2024-12-23 20:25 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +using namespace std::chrono_literals;
https://github.com/ROAR-QUTRC/perseus-v2/commit/c25fdc55fd217abeaf8404123171adb2f54c9e81

2024-12-23 20:33 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +                    decompressed.push_back(repeat_val);
https://github.com/ROAR-QUTRC/perseus-v2/commit/d627901e3c703674e80c684f6af5d5539323fbda

2024-12-23 23:34 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    serv_addr.sin_family = AF_INET;
https://github.com/ROAR-QUTRC/perseus-v2/commit/c8b5d9cd3db02220b06e9c24ba390f55c74d5580

2024-12-23 23:35 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    if (!this->connectToSensor(_sensorAddress, _sensorPort))
https://github.com/ROAR-QUTRC/perseus-v2/commit/c8b5d9cd3db02220b06e9c24ba390f55c74d5580

2024-12-23 23:35 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    }
https://github.com/ROAR-QUTRC/perseus-v2/commit/3839570adaa8c0b805988f04317a43e68c3f4fe3

2024-12-23 23:36 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +bool M2M2Lidar::connectToSensor(const std::string& host, int port)
https://github.com/ROAR-QUTRC/perseus-v2/commit/c8b5d9cd3db02220b06e9c24ba390f55c74d5580

2024-12-24 02:52 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +    ~M2M2Lidar();
Rule of Three: https://github.com/ROAR-QUTRC/perseus-v2/commit/d9d4597b1db93223b79f028e363fa4e899f42762

Rule of Five: https://github.com/ROAR-QUTRC/perseus-v2/commit/6a2e2ecebb31aab8d995c88eb977afffd43d985a

2024-12-24 03:15 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    command.push_back(static_cast<uint8_t>(config.angularResolution * 100));
https://github.com/ROAR-QUTRC/perseus-v2/commit/67833ab1a69d70afafbdcc94d1aa19be29f17516

2024-12-24 03:53 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +};
https://github.com/ROAR-QUTRC/perseus-v2/commit/62122747a5f454fde1be0914528a4420832b718e

2024-12-24 04:27 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    return decoded;
https://github.com/ROAR-QUTRC/perseus-v2/commit/bcb46c3fbf52f4393b2dec165d75a62b0042092d

2024-12-24 04:28 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    return decoded;
EVP implemented.

2024-12-24 04:40 UTC, DingoOz commented
Thanks @RandomSpaceship. Should all be updated now and much more standards compliant. Apologies for some embarrassing mistakes in there. Hopefully it makes much more sense now. 

I used the VESC clamping for clamping before casts.

I have tested this node with physical hardware and it runs and appears to provide sensible data.  I have captured and issue for a feature request to optimise the network usage, this is just streaming right now. I will also need to add taking IP address and port as a parameter, then hopefully we use static IP addresses and set them in the perseus bringup launch. 

Thanks for taking the time to review in full and thanks for sharing your deep knowledge.

2024-12-24 06:41 UTC, RandomSpaceship reviewed
Thanks for the hard work! Just a few minor things then it'll probably be good to merge. I'd suggest doing a `git reset cfb0ad913c3df1f983b33d8bc0a37e78c6871406` and re-writing the commit history though, you have a lot of commits which should get merged together and that'll probably be a lot easier than an interactive rebase.

Just keep in mind that you'll need to force-push after doing that.

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +};
why the second class? you've implemented everything into `M2M2Lidar`, did you intend to name that one with the `Node` suffix? Currently this one's not doing anything so you should probably delete it

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/package.xml
> +  <description>TODO: Package description</description>
probably worth adding a description. pretty minor. Keep in mind you'll need to regenerate Nix packaging after that though.

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    snprintf(portString, sizeof(portString), "%d", _sensorPort);
you should use either `std::format` or `std::to_string` here. Or better yet, just get the port as a string to start with and don't convert back and forth

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    if ((addressStatus = getaddrinfo(_sensorAddress.c_str(), portString, &addressHints, &addressResults)) != 0)
not going to comment on all this since it'll be replaced with the networking library

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +                pos += 2;
why the double-up?

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        std::copy_n(decompressed.data() + i + 4, sizeof(float), reinterpret_cast<uint8_t*>(&angle));
worth noting that floats aren't _guaranteed_ to be stored the same way on all systems. Probably not an issue here though

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +}
same note as for the header - should this be deleted?

2024-12-24 06:41 UTC, RandomSpaceship commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +}
personally I'd put this with the rest of the class member definitions, but this is fine too

2024-12-25 20:10 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/include/m2m2_lidar/m2m2_lidar.hpp
> +};
https://github.com/ROAR-QUTRC/perseus-v2/commit/c78d952603e30a60174a26137bdcc4f76609b7ea

2024-12-25 20:15 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +                pos += 2;
https://github.com/ROAR-QUTRC/perseus-v2/commit/4b0248205fb087bced3276eb9dc7f1fc7cd46861

2024-12-25 20:35 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +        std::copy_n(decompressed.data() + i + 4, sizeof(float), reinterpret_cast<uint8_t*>(&angle));
https://github.com/ROAR-QUTRC/perseus-v2/commit/69374f25bc1f4c22801f9097cc745aa0d08d2954

2024-12-25 20:35 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +}
https://github.com/ROAR-QUTRC/perseus-v2/commit/c78d952603e30a60174a26137bdcc4f76609b7ea

2024-12-25 20:46 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +    snprintf(portString, sizeof(portString), "%d", _sensorPort);
https://github.com/ROAR-QUTRC/perseus-v2/commit/9506a29b7ed87291367dee0285ae74fe52739719

2024-12-25 20:59 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/package.xml
> +  <description>TODO: Package description</description>
https://github.com/ROAR-QUTRC/perseus-v2/commit/c0ecfef92eb3460942f6ef5d1eca11c5a7653724

2024-12-25 21:06 UTC, DingoOz commented on software/ros_ws/src/perseus_sensors/src/m2m2_lidar/m2m2_lidar.cpp
> +}
https://github.com/ROAR-QUTRC/perseus-v2/commit/f9436ea6132f7141df65c28f6333837ceeaec93a

2024-12-25 23:58 UTC, DingoOz commented
> Thanks for the hard work! Just a few minor things then it'll probably be good to merge. I'd suggest doing a `git reset cfb0ad913c3df1f983b33d8bc0a37e78c6871406` and re-writing the commit history though, you have a lot of commits which should get merged together and that'll probably be a lot easier than an interactive rebase.
> 
> Just keep in mind that you'll need to force-push after doing that.

I have made updates to address feedback. I have then done my best to sensibly rebase all the small commits. As it was I went through and did an interactive rebase. Hopefully the commits are logically grouped up now. 

That should put this code in v1.0 state (pending future features such as parameter inputs and using a new network library(

@RandomSpaceship Thanks again for the deep review.

2024-12-26 01:37 UTC, RandomSpaceship approved these changes
Looks good.

2024-12-26 01:44 UTC, merged